name: Compile, test and check the docs

on:
  workflow_call: 

jobs:

  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format.yaml@v1
    secrets: inherit

  test:
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: 8.8.1
          - ghc: latest

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - uses: nikita-volkov/build-and-test-cabal-package.github-action@master
        with:
          ghc: ${{matrix.ghc}}
